version: '3.0'
services:
    app:
        image: cyrenity/celery-boilerplate
        hostname: "app-01"
        container_name: "app-server"
        ports:
            - "8080:80"
        links:
            - rabbitmq
        depends_on:
            - rabbitmq

    rabbitmq:
        image: rabbitmq:management-alpine
        hostname: "rabbitmq"
        container_name: "rabbitmq-server"
        ports:
            - "15672:15672"
            - "5672:5672"
