---

- name: Copy gunicorn app main file
  copy: 
    src: "{{ playbook_dir }}/../app.py"
    dest: "{{ app_dir }}/app.py"
  notify: restart gunicorn
  tags:
    - setup


- name: Copy celery tasks file
  copy: 
    src: "{{ playbook_dir }}/../tasks.py"
    dest: "{{ app_dir }}/tasks.py"
  notify: restart celery
  tags:
    - setup


