---
- name: set timezone
  timezone: name="Asia/Karachi"

- name: Create the app folder 
  file: path={{ app_dir }}
        owner={{ app_user }}
        group={{ app_group  }}
        mode=0774
        state=directory
  tags:
    - setup

