---
- name: Create the Nginx configuration file
  template: src=nginx.conf.j2
            dest=/etc/nginx/sites-available/{{ app_name }}
            backup=yes
  notify: reload nginx
  tags:
    - setup
    - update_nginx


- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx
  tags:
    - setup
    - update_nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ app_name }}
        dest=/etc/nginx/sites-enabled/{{ app_name }}
        state=link
  notify: reload nginx
  tags:
    - setup
    - update_nginx

